services:
    reverse-proxy:
        image: traefik:v2.11
        container_name: traefik
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        ports:
            - 80:80
            - 443:443
            - 6379:6379
            - 5432:5432
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./config/config.yml:/etc/traefik/config.yml:ro
            - ./certs:/etc/certs:ro
        networks:
            - mired
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik=true"
networks:
    mired:
        external: true
