http:
  routers:
    traefik:
      rule: "Host(`traefik.universidad.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "universidad.localhost"
            sans:
              - "*.universidad.localhost"
          - main: "universidad.local"
            sans:
              - "*.universidad.local"

tls:
  certificates:
    - certFile: "/etc/certs/cert.pem"
      keyFile: "/etc/certs/key.pem"
